### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by Offerel** [kaymmm/rhythmbox-lastfm-sync#7]
How do i install and use this? Sorry but i'm new to Rhythmbox.

**Comment by kaymmm** [comment]
just wrote a readme for you!

**Comment by Offerel** [comment]
Nice. You are my hero for today! Will try it in the evening, when I'm back at my own laptop.

BTW: I'm currently only on a phone and can't check it, but for me the most important thing is that it sync the lastplayed timestamp. Hopefully it does that.

If not, can you please add this to the script?

**Comment by kaymmm** [comment]
Yup, it's already there :) I just added the timestamp to the info output.

**Comment by kaymmm** [comment]
quick heads up, if you already set up the script, you'll have to tweak your config file to convert it from a .cfg to .yaml (see readme)
